[package]
name = "request_rust_server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[lib]
name = "request_server"
crate-type = ["rlib", "cdylib"]

